/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;
import org.checkerframework.checker.units.qual.A;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;

public class App {


    public static void main(String[] args) throws IOException, URISyntaxException{
       App app = new App();

       Class class1=app.getClass();

       URL url=class1.getResource("../../inputImage.bmp/");

       File file =new File(url.toURI());

       BufferedImage image=ImageIO.read(file);

       Bitmap example = new Bitmap("ExampleImage", "./app/src/main/resources", url.getPath());

       example.cyanBorder();
    }
}
