/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;


public class App {

    public static void main(String[] args) {
        Bitmap map;
        switch(args.length)
        {
            case 0:
                map = new Bitmap();
                break;
            case 1:
                map = new Bitmap(args[0]);
                map.read();
                break;
            case 2:
                map = new Bitmap(args[0],args[1]);
                map.write();
                break;
            case 3:
                map = new Bitmap(args[0],args[1],args[2]);
                map.write();
                break;
            default:
                System.out.println("Many args");
        }
    }
}
